### ISSUE TITLE
Figure out best connection between frontend and backend

### ISSUE THREAD

**Issue by denis-vyzulin** [dintear/evrika-mentoring#11]
**Description:** Create connection between frontend and backend sides through the API in a clear and readable way is complicated.

**Tasks:**
- [ ] 1. Find the best way to define models at frontend side
- [ ] 2. Create models and API views at backend side
- [ ] 3. And get data at frontend side (put the code in /src/models)
